# Pre-commit hooks
# 1. Run ruff on all python files
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.0
  hooks:
    # Run the linter.
    # - id: ruff
    # Run the formatter.
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
    - id: ruff-format

- repo: local
  hooks:
    - id: uv-build
      name: UV Build
      entry: uv run build
      language: system
      pass_filenames: false
