title: Alman Institut
description: A Simplified German Dialect
baseurl: ""
url: "https://alman.ai"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Set the permalink for posts so they render under /blog/
permalink: /blog/:title/