[project]
name = "alman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jsonschema>=4.23.0",
    "pydantic>=2.10.6",
    "pytest>=8.3.4",
]
